swagger: "2.0"
info:
  description: "This is a sample application server to produce APR and IRR for given input as a JSON payload"
  version: "1.0.0"
  title: "spotcap"
  contact:
    email: "whitehorse5353@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/"
tags:
  - name: "APR and IRR"
    description: "Everything about your Annual Percentage Rate and Internal Rate of Return"
schemes:
  - "http"
paths:
  /calculate-apr-irr:
    post:
      tags:
        - "APR and IRR"
      summary: "Compute APR & IRR"
      description: ""
      operationId: "computeAPR_IRR"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Cash flow object that needs to be sent"
          required: true
          schema:
            $ref: "#/definitions/APR_IRR"
      responses:
        405:
          description: "Invalid input"
definitions:
  APR_IRR:
    type: "object"
    required:
      - "upfrontFee"
      - "schedule"
    properties:
      principal:
        type: "number"
      upfrontFee:
        $ref: "#/definitions/UpfrontFee"
      schedule:
        type: "array"
        items:
          $ref: "#/definitions/Schedule"
  UpfrontFee:
    type: "object"
    required:
      - "value"
    properties:
      value:
        type: "number"
  Schedule:
    type: "object"
    required:
      - "principal"
      - "interestFee"
    properties:
      id:
        type: "number"
      date:
        type: "string"
      principal:
        type: "number"
      interestFee:
        type: "number"

externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
